insert into role (name) values ('ROLE_ADMIN');
insert into role (name) values ('ROLE_USER');


insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'admin@gmail.com', 'ww', 'rr', '$2a$10$sV9neIktpTCoeGpSSCUcs.sGYfrjamkwEQtrLAfo0JVH71g5JId6W', 'admin', 4.74);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'aklimczak0@printfriendly.com', 'Aimee', 'Klimczak', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'aklimczak0', 4.74);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'ajelkes1@paginegialle.it', 'Adi', 'Jelkes', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'ajelkes1', 2.75);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'afryman2@free.fr', 'Abbey', 'Fryman', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'afryman2', 43.5);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'hsearston3@smh.com.au', 'Harri', 'Searston', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'hsearston3', 174.02);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'wproctor4@elpais.com', 'Wade', 'Proctor', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'wproctor4', 151.44);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'tdowtry5@acquirethisname.com', 'Tana', 'Dowtry', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'tdowtry5', 16.12);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'beck6@opensource.org', 'Brnaba', 'Eck', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'beck6', 82.48);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'blowten7@nymag.com', 'Basilius', 'Lowten', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'blowten7', 134.66);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'mfranciskiewicz8@simplemachines.org', 'Martguerita', 'Franciskiewicz', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'mfranciskiewicz8', 75.33);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'sofarrell9@gnu.org', 'Sigvard', 'O''Farrell', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'sofarrell9', 154.75);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'uconnaughtona@nbcnews.com', 'Urson', 'Connaughton', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'uconnaughtona', 178.62);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'bhaquinb@google.com.hk', 'Benyamin', 'Haquin', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'bhaquinb', 62.19);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'fstuddertc@yandex.ru', 'Francene', 'Studdert', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'fstuddertc', 67.66);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'apottelld@imdb.com', 'Adolpho', 'Pottell', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'apottelld', 186.2);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'gpabele@histats.com', 'Grethel', 'Pabel', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'gpabele', 167.87);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'tmcpaikef@gov.uk', 'Theo', 'McPaike', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'tmcpaikef', 71.23);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'ghunnicuttg@upenn.edu', 'Garrard', 'Hunnicutt', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'ghunnicuttg', 18.3);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'nellerbeckh@upenn.edu', 'Noelle', 'Ellerbeck', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'nellerbeckh', 82.36);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'smoneypennyi@amazon.com', 'Sarge', 'Moneypenny', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'smoneypennyi', 37.02);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'cdichej@miibeian.gov.cn', 'Carolynn', 'Diche', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'cdichej', 12.28);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'lwilcocksk@blogspot.com', 'Lyn', 'Wilcocks', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'lwilcocksk', 14.85);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'jwillmentl@purevolume.com', 'Jeane', 'Willment', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'jwillmentl', 72.68);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'rshortonm@unicef.org', 'Ram', 'Shorton', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'rshortonm', 49.87);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'mkuhndeln@soup.io', 'Murry', 'Kuhndel', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'mkuhndeln', 7.7);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'vmaytumo@istockphoto.com', 'Vaughan', 'Maytum', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'vmaytumo', 125.99);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'nwybornp@surveymonkey.com', 'Nathaniel', 'Wyborn', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'nwybornp', 140.14);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'kdreigherq@nbcnews.com', 'Kristo', 'Dreigher', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'kdreigherq', 123.47);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'gfarmanr@google.nl', 'Gaspard', 'Farman', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'gfarmanr', 142.24);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'jphlippsens@goo.ne.jp', 'Jeni', 'Phlippsen', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'jphlippsens', 18.42);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'adigginsont@earthlink.net', 'Alfie', 'Digginson', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'adigginsont', 190.4);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'lwillettu@istockphoto.com', 'Lory', 'Willett', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'lwillettu', 135.36);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'wallsworthv@about.com', 'Will', 'Allsworth', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'wallsworthv', 10.48);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'dmullochw@goodreads.com', 'Drucie', 'Mulloch', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'dmullochw', 17.99);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'gchatenierx@oracle.com', 'Griffie', 'Chatenier', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'gchatenierx', 147.41);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'wmanjiny@mac.com', 'Weston', 'Manjin', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'wmanjiny', 102.08);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'aallpressz@epa.gov', 'Adey', 'Allpress', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'aallpressz', 128.55);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'lbigham10@washington.edu', 'Laurella', 'Bigham', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'lbigham10', 127.35);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'gbuckenham11@dailymail.co.uk', 'Gavan', 'Buckenham', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'gbuckenham11', 71.3);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'lmccarron12@dropbox.com', 'Letisha', 'McCarron', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'lmccarron12', 192.38);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'cgianotti13@mediafire.com', 'Care', 'Gianotti', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'cgianotti13', 68.37);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'atant14@deliciousdays.com', 'Abagael', 'Tant', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'atant14', 119.6);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'pbeggini15@ustream.tv', 'Pierce', 'Beggini', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'pbeggini15', 62.02);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'ssherburn16@yale.edu', 'Scarlet', 'Sherburn', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'ssherburn16', 44.03);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'kstanbro17@1und1.de', 'Kelsey', 'Stanbro', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'kstanbro17', 108.26);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'mvauls18@ocn.ne.jp', 'Miguelita', 'Vauls', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'mvauls18', 191.38);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'sgerrelts19@miitbeian.gov.cn', 'Samuele', 'Gerrelts', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'sgerrelts19', 161.37);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'cpaulsen1a@tinyurl.com', 'Cross', 'Paulsen', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'cpaulsen1a', 59.71);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'nfeore1b@ucoz.com', 'Nevile', 'Feore', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'nfeore1b', 179.65);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'esatchell1c@tinypic.com', 'Erasmus', 'Satchell', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'esatchell1c', 63.56);
insert into user (active, email, first_name, last_name, password, user_name, wallet_balance) values (1, 'rcrannage1d@census.gov', 'Randa', 'Crannage', '$2a$10$1aErbVHioBbczPsQSUi.Cuh4S4Rmgn4jl6rcJxN5ILRiSsqMiZYxq', 'rcrannage1d', 163.72);

insert into user_roles values (1,1);
insert into user_roles values (1,2);
insert into user_roles (user_id, roles_id) values (2, 2);
insert into user_roles (user_id, roles_id) values (3, 2);
insert into user_roles (user_id, roles_id) values (4, 2);
insert into user_roles (user_id, roles_id) values (5, 2);
insert into user_roles (user_id, roles_id) values (6, 2);
insert into user_roles (user_id, roles_id) values (7, 2);
insert into user_roles (user_id, roles_id) values (8, 2);
insert into user_roles (user_id, roles_id) values (9, 2);
insert into user_roles (user_id, roles_id) values (10, 2);
insert into user_roles (user_id, roles_id) values (11, 2);
insert into user_roles (user_id, roles_id) values (12, 2);
insert into user_roles (user_id, roles_id) values (13, 2);
insert into user_roles (user_id, roles_id) values (14, 2);
insert into user_roles (user_id, roles_id) values (15, 2);
insert into user_roles (user_id, roles_id) values (16, 2);
insert into user_roles (user_id, roles_id) values (17, 2);
insert into user_roles (user_id, roles_id) values (18, 2);
insert into user_roles (user_id, roles_id) values (19, 2);
insert into user_roles (user_id, roles_id) values (20, 2);
insert into user_roles (user_id, roles_id) values (21, 2);
insert into user_roles (user_id, roles_id) values (22, 2);
insert into user_roles (user_id, roles_id) values (23, 2);
insert into user_roles (user_id, roles_id) values (24, 2);
insert into user_roles (user_id, roles_id) values (25, 2);
insert into user_roles (user_id, roles_id) values (26, 2);
insert into user_roles (user_id, roles_id) values (27, 2);
insert into user_roles (user_id, roles_id) values (28, 2);
insert into user_roles (user_id, roles_id) values (29, 2);
insert into user_roles (user_id, roles_id) values (30, 2);
insert into user_roles (user_id, roles_id) values (31, 2);
insert into user_roles (user_id, roles_id) values (32, 2);
insert into user_roles (user_id, roles_id) values (33, 2);
insert into user_roles (user_id, roles_id) values (34, 2);
insert into user_roles (user_id, roles_id) values (35, 2);
insert into user_roles (user_id, roles_id) values (36, 2);
insert into user_roles (user_id, roles_id) values (37, 2);
insert into user_roles (user_id, roles_id) values (38, 2);
insert into user_roles (user_id, roles_id) values (39, 2);
insert into user_roles (user_id, roles_id) values (40, 2);
insert into user_roles (user_id, roles_id) values (41, 2);
insert into user_roles (user_id, roles_id) values (42, 2);
insert into user_roles (user_id, roles_id) values (43, 2);
insert into user_roles (user_id, roles_id) values (44, 2);
insert into user_roles (user_id, roles_id) values (45, 2);
insert into user_roles (user_id, roles_id) values (46, 2);
insert into user_roles (user_id, roles_id) values (47, 2);
insert into user_roles (user_id, roles_id) values (48, 2);
insert into user_roles (user_id, roles_id) values (49, 2);
insert into user_roles (user_id, roles_id) values (50, 2);
insert into user_roles (user_id, roles_id) values (51, 2);

insert into sport (name) values ('Football');
insert into sport (name) values ('Basketball');
insert into sport (name) values ('Volleyball');
insert into sport (name) values ('Handball');
insert into sport (name) values ('Tennis');

insert into bet_category (name) values ('Result 1X2');
insert into bet_category (name) values ('Halftime 1X2');
insert into bet_category (name) values ('Both teams to score?');

insert into bet_category_sports (sports_id, bet_category_id) VALUES (1,1);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (1,3);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (2,1);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (2,2);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (2,3);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (3,1);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (3,2);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (3,3);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (4,1);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (4,2);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (4,3);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (5,1);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (5,2);
insert into bet_category_sports (sports_id, bet_category_id) VALUES (5,3);

insert into subscription_topic (name) values ('General');
insert into subscription_topic (name) values ('Football');
insert into subscription_topic (name) values ('Basketball');
insert into subscription_topic (name) values ('Volleyball');
insert into subscription_topic (name) values ('Handball');
insert into subscription_topic (name) values ('Tennis');

insert into team (name, sport_id) values ('Arsenal', 1);
insert into team (name, sport_id) values ('Bournemouth', 1);
insert into team (name, sport_id) values ('Brighton & Hove Albion', 1);
insert into team (name, sport_id) values ('Burnley', 1);
insert into team (name, sport_id) values ('Chelsea', 1);
insert into team (name, sport_id) values ('Crystal Palace', 1);
insert into team (name, sport_id) values ('Chelsea', 1);
insert into team (name, sport_id) values ('Everton', 1);
insert into team (name, sport_id) values ('Huddersfield Town', 1);
insert into team (name, sport_id) values ('Leicester City', 1);
insert into team (name, sport_id) values ('Liverpool', 1);
insert into team (name, sport_id) values ('Manchester City', 1);
insert into team (name, sport_id) values ('Manchester United', 1);
insert into team (name, sport_id) values ('Newcastle United', 1);
insert into team (name, sport_id) values ('Southampton', 1);
insert into team (name, sport_id) values ('Swansea City', 1);
insert into team (name, sport_id) values ('Tottenham Hotspur', 1);
insert into team (name, sport_id) values ('Watford', 1);
insert into team (name, sport_id) values ('West Bromwich Albion', 1);
insert into team (name, sport_id) values ('West Ham United', 1);

insert into team (name, sport_id) values ('Rafael Nadal', 5);
insert into team (name, sport_id) values ('Roger	Federer', 5);
insert into team (name, sport_id) values ('Marin	Cilic', 5);
insert into team (name, sport_id) values ('Grigor Dimitrov', 5);
insert into team (name, sport_id) values ('Alexander	Zverev', 5);
insert into team (name, sport_id) values ('Dominic	Thiem', 5);
insert into team (name, sport_id) values ('David	Goffin', 5);
insert into team (name, sport_id) values ('Jack Sock', 5);
insert into team (name, sport_id) values ('Juan Martin', 5);
insert into team (name, sport_id) values ('Pablo Carreno', 5);
insert into team (name, sport_id) values ('Kevin	Anderson', 5);
insert into team (name, sport_id) values ('Sam	Querrey', 5);
insert into team (name, sport_id) values ('Pablo Carreno', 5);
insert into team (name, sport_id) values ('Novak	Djokovic', 5);
insert into team (name, sport_id) values ('Nick	Kyrgios', 5);
insert into team (name, sport_id) values ('Stan	Wawrinka', 5);
insert into team (name, sport_id) values ('Tomas	Berdych', 5);
insert into team (name, sport_id) values ('Lucas	Pouille', 5);
insert into team (name, sport_id) values ('John	Isner', 5);
insert into team (name, sport_id) values ('Jo-Wilfried	Tsonga', 5);
insert into team (name, sport_id) values ('Andy Murray', 5);

insert into team (name, sport_id) values ('CSKA Moscow', 2);
insert into team (name, sport_id) values ('Fenerbahęe', 2);
insert into team (name, sport_id) values ('Real Madrid', 2);
insert into team (name, sport_id) values ('Olympiacos', 2);
insert into team (name, sport_id) values ('Panathinaikos', 2);
insert into team (name, sport_id) values ('FC Barcelona', 2);
insert into team (name, sport_id) values ('Baskonia', 2);
insert into team (name, sport_id) values ('Anadolu Efes', 2);
insert into team (name, sport_id) values ('Lokomotiv Kuban', 2);
insert into team (name, sport_id) values ('Gran Canaria', 2);
insert into team (name, sport_id) values ('Crvena Zvezda', 2);
insert into team (name, sport_id) values ('Khimki', 2);
insert into team (name, sport_id) values ('Galatasaray', 2);
insert into team (name, sport_id) values ('Zalgiris', 2);
insert into team (name, sport_id) values ('Unicaja', 2);
insert into team (name, sport_id) values ('UNICS', 2);
insert into team (name, sport_id) values ('Maccabi Tel Aviv', 2);
insert into team (name, sport_id) values ('Valencia Basket', 2);
insert into team (name, sport_id) values ('Bayern Munich', 2);

insert into team (name, sport_id) values ('Kazan', 3);
insert into team (name, sport_id) values ('Modena Volley', 3);
insert into team (name, sport_id) values ('Volley Treviso', 3);
insert into team (name, sport_id) values ('Dinamo Bucuresti', 3);
insert into team (name, sport_id) values ('Porto Ravenna', 3);
insert into team (name, sport_id) values ('Trentino Volley', 3);
insert into team (name, sport_id) values ('Belgorod', 3);
insert into team (name, sport_id) values ('Pallavolo Parma', 3);
insert into team (name, sport_id) values ('Brno', 3);
insert into team (name, sport_id) values ('Leipzig', 3);
insert into team (name, sport_id) values ('CLIS Torino Pallavolo', 3);
insert into team (name, sport_id) values ('Friedrichshafen', 3);
insert into team (name, sport_id) values ('CSKA Sofia', 3);
insert into team (name, sport_id) values ('Dukla Liberec', 3);
insert into team (name, sport_id) values ('Plomien Milowice', 3);



